#!/bin/bash
# V4 Resume from step 300: per-turn LLM judge + retrieval-hit, no positional prior

cd /root/paddlejob/workspace/new_mem1/mem1/mem1/Mem1/train
export PATH=/root/miniconda3/envs/mem1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5
export VLLM_ATTENTION_BACKEND=FLASH_ATTN
export RAY_TMPDIR=/tmp/ray-v4
export RAY_memory_usage_threshold=0.99
export RAY_memory_monitor_refresh_ms=0
export PYTHONUNBUFFERED=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

unset http_proxy
unset https_proxy
unset HTTP_PROXY
unset HTTPS_PROXY

python3 -m grpo_v3.main_ppo_v3 \
  data.train_files=data/nq_hotpotqa_train_multi_2/train.parquet \
  data.val_files=data/nq_hotpotqa_train_multi_2/test.parquet \
  data.train_data_num=null \
  data.val_data_num=null \
  data.train_batch_size=96 \
  data.val_batch_size=96 \
  data.max_prompt_length=4096 \
  data.max_response_length=500 \
  data.max_start_length=2048 \
  data.max_obs_length=500 \
  data.shuffle_train_dataloader=True \
  algorithm.adv_estimator=grpo \
  +algorithm.dapo_max_retries=1 \
  +algorithm.dapo_start_step=0 \
  +algorithm.dapo_process_thresh=0.01 \
  actor_rollout_ref.model.path=/root/paddlejob/workspace/new_mem1/mem1/mem1/Mem1/train/verl_checkpoints/V3-grpo-n4-bs96-resume220/actor/global_step_300 \
  actor_rollout_ref.actor.optim.lr=5e-7 \
  actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0 \
  actor_rollout_ref.model.enable_gradient_checkpointing=true \
  actor_rollout_ref.model.use_remove_padding=False \
  actor_rollout_ref.actor.use_kl_loss=false \
  actor_rollout_ref.actor.kl_loss_coef=0.001 \
  actor_rollout_ref.actor.kl_loss_type=low_var_kl \
  +actor_rollout_ref.actor.llds_lambda=0.1 \
  +actor_rollout_ref.actor.clip_higher=0.28 \
  actor_rollout_ref.actor.entropy_coeff=0.001 \
  ++actor_rollout_ref.actor.entropy_target=0.6 \
  ++actor_rollout_ref.actor.entropy_coeff_max=0.05 \
  actor_rollout_ref.actor.ppo_mini_batch_size=384 \
  actor_rollout_ref.actor.ppo_micro_batch_size=12 \
  actor_rollout_ref.actor.fsdp_config.param_offload=True \
  actor_rollout_ref.actor.fsdp_config.grad_offload=false \
  actor_rollout_ref.actor.fsdp_config.optimizer_offload=false \
  actor_rollout_ref.actor.state_masking=true \
  actor_rollout_ref.rollout.log_prob_micro_batch_size=12 \
  actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
  actor_rollout_ref.rollout.name=vllm \
  actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
  actor_rollout_ref.rollout.n_agent=4 \
  actor_rollout_ref.rollout.temperature=1 \
  actor_rollout_ref.ref.log_prob_micro_batch_size=12 \
  actor_rollout_ref.ref.fsdp_config.param_offload=True \
  algorithm.kl_ctrl.kl_coef=0.001 \
  algorithm.no_think_rl=false \
  trainer.critic_warmup=0 \
  "trainer.logger=['swanlab','console']" \
  +trainer.val_only=false \
  +trainer.val_before_train=false \
  trainer.default_hdfs_dir=null \
  trainer.n_gpus_per_node=6 \
  trainer.nnodes=1 \
  trainer.save_freq=20 \
  trainer.test_freq=-1 \
  trainer.project_name=MEM1 \
  trainer.experiment_name=V4-grpo-n4-bs96-resume300 \
  trainer.total_epochs=1 \
  trainer.total_training_steps=800 \
  trainer.default_local_dir=verl_checkpoints/V4-grpo-n4-bs96-resume300 \
  max_turns=6 \
  do_search=true \
  retriever.url=http://127.0.0.1:8013/retrieve \
  retriever.topk=3 \
  +curriculum.init_phase=transition \
  +curriculum.ema_em_init=0.35 \
  +curriculum.ema_format_init=0.99 \
  +curriculum.warmup_format_thresh=0.9 \
  +curriculum.warmup_max_step=80 \
  +curriculum.convergence_em_thresh=0.15 \
  +curriculum.convergence_max_step=300 \
  +curriculum.transition_em_thresh=0.60 \
  +curriculum.transition_max_step=9999 \
  +reward.turn_weight_alpha=0.3 \
  +reward.turn_weight_gamma=1.5 \
  2>&1 | tee V4-grpo-n4-bs96-resume300.log
